project:
  type: website

website:
  twitter-card: true
  open-graph: true
  search:
    location: navbar
    type: overlay
  #title: "Personal website of Alexander Vossen"
  #favicon: alex.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd 
        text: Blog
      - href: research.qmd
        text: Research
      - href: news.qmd
        text: News
 
 
  page-footer: 
    center: 
      - text: "Privacy Policy/Datenschutz"
        href: privacy.qmd
      - text: "Imprint/Impressum"
        href: imprint.qmd
        
format:
  html:
    theme: Sandstone
  #  theme: [tiu.scss]
  #  css: styles.css
    toc: true
    dark-mode: true

#margin-header: |
#  ![](JADS_logo_BLACK.jpg)
  
editor: visual

resources:
  - images/
